version: "3"
services:
  frontend:
    build: ./frontend
    image: frontend
    environment:
      PORT: 8080
      AUTH_API_ADDRESS: http://auth-api:8081
      TODOS_API_ADDRESS: http://todos-api:8082
      ELASTIC_APM_SERVER_URL: ${SERVER}
    ports:
      - 8080:8080
    networks:
    - demo_apm_microservice_elastic
    depends_on:
      - auth-api
      - todos-api
      - users-api

  auth-api:
    build: ./auth-api
    image: auth-api
    environment:
      AUTH_API_PORT: 8081
      JWT_SECRET: myfancysecret
      USERS_API_ADDRESS: http://users-api:8083
      ELASTIC_APM_SECRET_TOKEN: "${TOKEN}"
      ELASTIC_APM_SERVER_URL: "${SERVER}"
      ELASTIC_APM_LOG_FILE: "stdout"
      ELASTIC_APM_LOG_LEVEL: "debug"
    networks:
    - demo_apm_microservice_elastic
    depends_on:
      - users-api

  todos-api:
    build: ./todos-api
    image: todos-api
    environment:
      TODO_API_PORT: 8082
      JWT_SECRET: myfancysecret
      REDIS_HOST: redis-queue
      REDIS_PORT: 6379
      REDIS_CHANNEL: log_channel
      ELASTIC_APM_SECRET_TOKEN: "${TOKEN}"
      ELASTIC_APM_SERVER_URL: "${SERVER}"
      ELASTIC_APM_LOG_LEVEL: "debug"
      DEBUG: todos-api:*
      DEBUG: express:*
    networks:
    - demo_apm_microservice_elastic
    depends_on:
      - redis-queue

  users-api:
    build: ./users-api
    image: users-api
    environment:
     SERVER_PORT: 8083
     JWT_SECRET: myfancysecret
     ELASTIC_APM_SECRET_TOKEN: "${TOKEN}"
     ELASTIC_APM_SERVER_URL: "${SERVER}"
     ELASTIC_APM_LOG_LEVEL: "DEBUG"
    networks:
    - demo_apm_microservice_elastic

  log-message-processor:
    build: ./log-message-processor
    image: log-message-processor
    environment:
      REDIS_HOST: redis-queue
      REDIS_PORT: 6379
      REDIS_CHANNEL: log_channel
      ELASTIC_APM_SECRET_TOKEN: "${TOKEN}"
      ELASTIC_APM_SERVER_URL: "${SERVER}"
      ELASTIC_APM_DEBUG: "True"
    networks:
    - demo_apm_microservice_elastic
    depends_on:
      - redis-queue

  redis-queue:
    image: redis
    networks:
    - demo_apm_microservice_elastic
    ports:
      - 6379:6379

networks:
  demo_apm_microservice_elastic:
    external: true